version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:7.3.3
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1


  db_source:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5433:5432'
    volumes:
      - db_source:/var/lib/postgresql/data

  db_dst:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5434:5432'
    volumes:
      - db_dst:/var/lib/postgresql/data

  producer:  # add producer service
    build: ./producer
    depends_on:
      - kafka
      - db_source
    environment:
      - DB_HOST=db_source
      - DB_PORT=5432
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
    volumes:
      - ./last_id.txt:/app/last_id.txt

  consumer: # add consumer service
    build: ./consumer
    depends_on:
      - kafka
      - db_dst
    environment:
      - DB_HOST=db_dst
      - DB_PORT=5432
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092

volumes:
  db_source:
    driver: local
  db_dst:
    driver: local
